 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/cera.id.au:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'asia.gcr.io/$PROJECT_ID/cera.id.au:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'ceraidau'
   - '--image'
   - 'asia.gcr.io/$PROJECT_ID/cera.id.au:$COMMIT_SHA'
   - '--region'
   - 'australia-southeast1'
   - '--platform'
   - 'managed'
 images:
 - 'asia.gcr.io/$PROJECT_ID/ceraidau:$COMMIT_SHA'
