baseURL: "https://cera.id.au/"
languageCode: en-au
title: cera
params:
  social:
    - icon: github
      href: "https://github.com/olliebun"
    - icon: envelope
      href: "mailto:ceralena.davies@gmail.com"
    - icon: twitter
      href: "https://twitter.com/cerabiner"
