
version: "3.4"

services:
  hugo:
    build:
      context: .
      target: hugo
    volumes:
      - .:/work
    working_dir: /work
    command: ["hugo", "server", "--watch", "--buildDrafts", "--bind", "0.0.0.0"]
    ports:
      - "1313:1313"

  node:
    build:
      context: .
      target: node
    volumes:
      - .:/work
    working_dir: /work
    command: ["yarn", "start"]

volumes:
  tmp: ~
