
version: "3.4"

services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/work
      - tmp:/tmp
    working_dir: /work
    command: bash
    ports:
      - "8080:8080"

volumes:
  tmp: ~
