
version: "3.4"

services:
  hugo:
    build:
      context: .
      target: hugo
    volumes:
      - .:/work
    working_dir: /work
    command: bash
    ports:
      - "8080:8080"

  node:
    build:
      context: .
      target: node
    volumes:
      - .:/work
    working_dir: /work
    command: ["yarn", "start"]

volumes:
  tmp: ~
