#!/bin/sh
set -ue

checkout=$SCRATCHDIR/co

git clone --branch "$VERSION" ssh://git@bitbucket.org/ceralena/cera.id.au "$checkout"

pushd "$checkout"
  ./scripts/prodbuild.sh

  rm -rf .git Makefile scripts README.md README.md README.md README.md

  pushd frontend
    rm -rf package.json webpack.config.js src yarn.lock node_modules .babelrc .flowconfig
  popd

  pushd backend
    rm -rf src vendor pkg
  popd

  cp -r * $BUILDDIR/
popd
