#!/bin/bash
set -uex

checkout=$SCRATCHDIR/co

if ! which unzip &>/dev/null; then
  echo "missing dependency: unzip"
fi

git clone --branch "$VERSION" git@bitbucket.org:ceralena/cera.id.au "$checkout"

pushd "$checkout"
  # fix the version in build.sbt
  sed -i -e "s/1.0-SNAPSHOT/$VERSION/" build.sbt

  # build the app
  make build-dist

  # unzip the build into the build dir
  unzip "target/universal/cera-id-au-$VERSION.zip" -d "$BUILDDIR"
popd

# undo the nesting done by 'sbt dist'
pushd "$BUILDDIR"
  mv "cera-id-au-$VERSION"/* .
  rm -d "cera-id-au-$VERSION"

  # remove stuff we don't need
  rm -r share bin/cera-id-au.bat
popd
